<a href="https://colab.research.google.com/github/AkashRio469/Crop-Whisperer/blob/main/Crop_Whisperer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Crop Whisperer

## Dataset
- **Name:** Crop Recommendation Dataset
- **Author:** Atharva Ingle (Kaggle)
- **Link:** [Crop Recommendation Dataset on Kaggle](https://www.kaggle.com/datasets/atharvaingle/crop-recommendation-dataset)
- **License:** [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
- **Source details:** Not documented on the dataset page

In [11]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("atharvaingle/crop-recommendation-dataset")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'crop-recommendation-dataset' dataset.
Path to dataset files: /kaggle/input/crop-recommendation-dataset

In [12]:
import os
print(os.listdir(path))

['Crop_recommendation.csv']

In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv(os.path.join(path, "Crop_recommendation.csv"))
df.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            2200 non-null   int64
 1   P            2200 non-null   int64
 2   K            2200 non-null   int64
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   object
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB

In [15]:
df.shape

(2200, 8)

 DATA

*  Rows    : 2200
*  Columns : 8


Column names :


*  N - ratio of Nitrogen content in soil
*  P - ratio of Phosphorous content in soil
*  K - ratio of Potassium content in soil
*  Temperature
*  Humidity
*  Ph
*  Rainfall
*  Label

Target Column :

*  Label(Crop_name)

In [16]:
df.describe()

,N,P,K,temperature,humidity,ph,rainfall
count,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000
mean,50.551818,53.362727,48.149091,25.616244,71.481779,6.469480,103.463655
std,36.917334,32.985883,50.647931,5.063749,22.263812,0.773938,54.958389
min,0.000000,5.000000,5.000000,8.825675,14.258040,3.504752,20.211267
25%,21.000000,28.000000,20.000000,22.769375,60.261953,5.971693,64.551686
50%,37.000000,51.000000,32.000000,25.598693,80.473146,6.425045,94.867624
75%,84.250000,68.000000,49.000000,28.561654,89.948771,6.923643,124.267508
max,140.000000,145.000000,205.000000,43.675493,99.981876,9.935091,298.560117

In [17]:
df['label'].value_counts()

label
rice           100
maize          100
chickpea       100
kidneybeans    100
pigeonpeas     100
mothbeans      100
mungbean       100
blackgram      100
lentil         100
pomegranate    100
banana         100
mango          100
grapes         100
watermelon     100
muskmelon      100
apple          100
orange         100
papaya         100
coconut        100
cotton         100
jute           100
coffee         100
Name: count, dtype: int64

## Day 2: Answers

**1. How many different crops are there?**
There are 22 crops (rice, maize, chickpea, kidneybeans, pigeonpeas,
mothbeans, mungbean, blackgram, lentil, pomegranate, banana, mango,
grapes, watermelon, muskmelon, apple, orange, papaya, coconut,
cotton, jute, coffee).

**2. Are they balanced?**
Yes. Every crop has exactly 100 rows (22 x 100 = 2200). This means
accuracy is a fair metric here, and random guessing would be right
only about 1 time in 22 (roughly 4.5%).

**3. Does anything in describe() look odd?**
- No missing values: every column has a count of 2200.
- pH ranges from 3.5 to 9.9. That is within the valid 0-14 scale,
  but both ends are quite extreme for soil, so worth checking later.
- Humidity ranges from 14.3 to 100, which is within 0-100.
- Potassium (K): 75% of rows are 49 or below, but the maximum is
  205. A few rows have very high K. I will check by crop before
  deciding if they are errors.
- Humidity: the median (80.5) is higher than the mean (71.5), so
  some low-humidity rows pull the average down.
- The columns are on very different scales (K up to 205, pH up to
  about 10), which matters for some models later.

In [20]:
df[['N', 'P', 'K']]

        N   P   K
0      90  42  43
1      85  58  41
2      60  55  44
3      74  35  40
4      78  42  42
...   ...  ..  ..
2195  107  34  32
2196   99  15  27
2197  118  33  30
2198  117  32  34
2199  104  18  30

[2200 rows x 3 columns]

In [21]:
df['ph'].head()

0    6.502985
1    7.038096
2    7.840207
3    6.980401
4    7.628473
Name: ph, dtype: float64

In [22]:
df[['temperature', 'humidity']].head()

   temperature   humidity
0    20.879744  82.002744
1    21.770462  80.319644
2    23.004459  82.320763
3    26.491096  80.158363
4    20.130175  81.604873

In [23]:
df[df['label'] == 'rice']

     N   P   K  temperature   humidity        ph    rainfall label
0   90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1   85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2   60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3   74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4   78  42  42    20.130175  81.604873  7.628473  262.717340  rice
..  ..  ..  ..          ...        ...       ...         ...   ...
95  88  46  42    22.683191  83.463583  6.604993  194.265172  rice
96  93  47  37    21.533463  82.140041  6.500343  295.924880  rice
97  60  55  45    21.408658  83.329319  5.935745  287.576694  rice
98  78  35  44    26.543481  84.673536  7.072656  183.622266  rice
99  65  37  40    23.359054  83.595123  5.333323  188.413665  rice

[100 rows x 8 columns]

In [24]:
df[df['label'] == 'rice'].shape

(100, 8)

In [25]:
df[(df['ph'] < 5) & (df['K'] > 100)]

Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []

In [26]:
df[df['ph'] < 5].shape

(62, 8)

In [27]:
df[df['ph'] < 5]['label'].value_counts()

label
pigeonpeas    24
mothbeans     20
mango         18
Name: count, dtype: int64

In [28]:
df.groupby('label')['N'].mean()

label
apple           20.80
banana         100.23
blackgram       40.02
chickpea        40.09
coconut         21.98
coffee         101.20
cotton         117.77
grapes          23.18
jute            78.40
kidneybeans     20.75
lentil          18.77
maize           77.76
mango           20.07
mothbeans       21.44
mungbean        20.99
muskmelon      100.32
orange          19.58
papaya          49.88
pigeonpeas      20.73
pomegranate     18.87
rice            79.89
watermelon      99.42
Name: N, dtype: float64

In [29]:
df.groupby('label')['K'].mean()

label
apple          199.89
banana          50.05
blackgram       19.24
chickpea        79.92
coconut         30.59
coffee          29.94
cotton          19.56
grapes         200.11
jute            39.99
kidneybeans     20.05
lentil          19.41
maize           19.79
mango           29.92
mothbeans       20.23
mungbean        19.87
muskmelon       50.08
orange          10.01
papaya          50.04
pigeonpeas      20.29
pomegranate     40.21
rice            39.87
watermelon      50.22
Name: K, dtype: float64

In [30]:
df.groupby('label')['N'].mean().sort_values()

label
lentil          18.77
pomegranate     18.87
orange          19.58
mango           20.07
pigeonpeas      20.73
kidneybeans     20.75
apple           20.80
mungbean        20.99
mothbeans       21.44
coconut         21.98
grapes          23.18
blackgram       40.02
chickpea        40.09
papaya          49.88
maize           77.76
jute            78.40
rice            79.89
watermelon      99.42
banana         100.23
muskmelon      100.32
coffee         101.20
cotton         117.77
Name: N, dtype: float64

In [31]:
df.groupby('label')['K'].mean().sort_values(ascending=False)

label
grapes         200.11
apple          199.89
chickpea        79.92
watermelon      50.22
muskmelon       50.08
banana          50.05
papaya          50.04
pomegranate     40.21
jute            39.99
rice            39.87
coconut         30.59
coffee          29.94
mango           29.92
pigeonpeas      20.29
mothbeans       20.23
kidneybeans     20.05
mungbean        19.87
maize           19.79
cotton          19.56
lentil          19.41
blackgram       19.24
orange          10.01
Name: K, dtype: float64

In [32]:
df.groupby('label')['K'].max().sort_values(ascending=False)

label
apple          205
grapes         205
chickpea        85
banana          55
watermelon      55
papaya          55
muskmelon       55
pomegranate     45
rice            45
jute            45
coconut         35
coffee          35
mango           35
blackgram       25
mothbeans       25
maize           25
lentil          25
kidneybeans     25
cotton          25
mungbean        25
pigeonpeas      25
orange          15
Name: K, dtype: int64

In [33]:
df.groupby('label')['K'].agg(['mean', 'max']).sort_values('mean', ascending=False)

               mean  max
label
grapes       200.11  205
apple        199.89  205
chickpea      79.92   85
watermelon    50.22   55
muskmelon     50.08   55
banana        50.05   55
papaya        50.04   55
pomegranate   40.21   45
jute          39.99   45
rice          39.87   45
coconut       30.59   35
coffee        29.94   35
mango         29.92   35
pigeonpeas    20.29   25
mothbeans     20.23   25
kidneybeans   20.05   25
mungbean      19.87   25
maize         19.79   25
cotton        19.56   25
lentil        19.41   25
blackgram     19.24   25
orange        10.01   15

In [34]:
df.groupby('label')['rainfall'].mean().sort_values()

label
muskmelon       24.689952
lentil          45.680454
mungbean        48.403601
watermelon      50.786219
mothbeans       51.198487
blackgram       67.884151
grapes          69.611829
chickpea        80.058977
cotton          80.398043
maize           84.766988
mango           94.704515
banana         104.626980
kidneybeans    105.919778
pomegranate    107.528442
orange         110.474969
apple          112.654779
papaya         142.627839
pigeonpeas     149.457564
coffee         158.066295
jute           174.792798
coconut        175.686646
rice           236.181114
Name: rainfall, dtype: float64

In [35]:
df.groupby('label')['temperature'].mean().sort_values(ascending=False)

label
papaya         33.723859
mango          31.208770
blackgram      29.973340
muskmelon      28.663066
mungbean       28.525775
mothbeans      28.194920
pigeonpeas     27.741762
coconut        27.409892
banana         27.376798
watermelon     25.591767
coffee         25.540477
jute           24.958376
lentil         24.509052
cotton         23.988958
grapes         23.849575
rice           23.689332
orange         22.765725
apple          22.630942
maize          22.389204
pomegranate    21.837842
kidneybeans    20.115085
chickpea       18.872847
Name: temperature, dtype: float64

In [36]:
df.groupby('label')['humidity'].mean().sort_values()

label
chickpea       16.860439
kidneybeans    21.605357
pigeonpeas     48.061633
mango          50.156573
mothbeans      53.160418
coffee         58.869846
lentil         64.804785
maize          65.092249
blackgram      65.118426
jute           79.639864
cotton         79.843474
banana         80.358123
grapes         81.875228
rice           82.272822
watermelon     85.160375
mungbean       85.499975
pomegranate    90.125504
orange         92.170209
apple          92.333383
muskmelon      92.342802
papaya         92.403388
coconut        94.844272
Name: humidity, dtype: float64

In [37]:
df.groupby('label')['temperature'].mean().idxmax()
df.groupby('label')['humidity'].mean().idxmin()

'chickpea'

## Project Questions

1. Do different crops really need different amounts of rainfall?
2. How do N, P and K differ from crop to crop, and which nutrient
   separates the crops most?
3. Are any of the soil and climate features strongly related to
   each other?
4. Are the unusual values (very high K, very low pH) concentrated
   in specific crops, or do they look like errors?
5. Can a model predict the right crop from soil and climate
   conditions, and which features matter most?